[colors.primary]
background = "#0F1A2D"
foreground = "#cdd6f4"


[colors.vi_mode_cursor]
text = "#0F1A2D"
cursor = "#9193f7"

[colors.search.matches]
foreground = "#0F1A2D"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#0F1A2D"
background = "#90dc89"

[colors.footer_bar]
foreground = "#0F1A2D"
background = "#a6adc8"

[colors.hints.start]
foreground = "#0F1A2D"
background = "#f6d484"

[colors.hints.end]
foreground = "#0F1A2D"
background = "#a6adc8"

[colors.selection]
text = "#0F1A2D"
background = "#edbbb1"

[colors.normal]
black = "#10192D"
red = "#ef6b91"
green = "#90dc89"
yellow = "#f6d484"
blue = "#59a8f8"
magenta = "#ee96d6"
cyan = "#41d2ba"
white = "#bac2de"

[colors.bright]
red = "#ef6b91"
green = "#90dc89"
yellow = "#f6d484"
blue = "#59a8f8"
magenta = "#ee96d6"
cyan = "#41d2ba"
white = "#a6adc8"

[colors.dim]
red = "#ef6b91"
green = "#90dc89"
yellow = "#f6d484"
blue = "#59a8f8"
magenta = "#ee96d6"
cyan = "#41d2ba"
white = "#bac2de"

[[colors.indexed_colors]]
index = 16
color = "#f18b74"

[[colors.indexed_colors]]
index = 17
color = "#edbbb1"
